name: lab9_week8
description: "Week 8 lab"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core UI packages
  cupertino_icons: ^1.0.8

  # Floor (SQLite abstraction) & sqflite engine
  floor: ^1.4.0
  sqflite: ^2.2.8+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints
  flutter_lints: ^5.0.0

  # Codegen for Floor
  floor_generator: ^1.4.0
  build_runner: ^2.5.4

flutter:
  uses-material-design: true
